xPaginationPage:
  name: X-Pagination-Page
  in: header
  required: false
  description: Nummer van de huidige pagina (paginanummering start bij 1)
  schema:
    type: integer
contentType:
  name: Content-Type
  in: header
  required: false
  description: Media type van het request
  schema:
    type: string
contentCrs:
  name: Content-Crs
  in: header
  required: false
  description: Coordinaatreferentiesysteem van de meegegeven geometrie
  schema:
    type: string
    enum:
      - 'epsg:4258'
      - 'epsg:28992'
    default: 'epsg:4258'
acceptCrs:
  name: Accept-Crs
  in: header
  required: false
  description: Gewenste CRS van de coördinaten in de response
  schema:
    type: string
    enum:
      - 'epsg:4258'
      - 'epsg:28992'
    default: 'epsg:4258'
